### ISSUE TITLE
Natural Selection master checklist

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#1]
## Design
- [x] **Sim folder and design doc created** (Date: //)
  - [x] Create sim folder in [PhET Sim Design Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYUUhvZnlCUDF0bGc) using phet-docs account
  - [x] Place design doc in the sim folder
- [x] **Legacy sim docs/info gathered**
  - [x] [Sim suggestions doc](https://phet.unfuddle.com/a#/projects/9404/notebooks/3863/pages/105821) reviewed
  - [x] Unfuddle tickets reviewed ([searching tickets](https://github.com/phetsims/phet-info/blob/master/issue-info/unfuddle-ticket-search.md))
- [x] **Learning goals and standards identified** (Date: //)
- [x] **Design concept complete**  (Date: //)
- [x] **Wireframes complete** (Date: //) 
- [x] **Mockups complete** (Date: //) 
  - [x] Mockups checked for colorblind and greyscale
- [x] **Features for PhET-iO discussion** 
- [x] **Interviews complete** (Date: //) 
  - [x] Results reported to team
  - [x] Notes pasted into design doc
  - [x] Back-up of interviews
- [x] **Lead designer "sign off"** (Date: //) 
  - [x] Performance acceptable
  - [x] Carefully review ?showPointerAreas
  - [x] No new feature requests
- [x] **Pre-publication items** 
  - [x] Auxilary screenshots (up to 3 additional)
  - [x] Accessories (keywords, categories, description, learning goals, related sims, NSDL)
  - [x] Teacher Guide created, uploaded, and added to sim design folder
  - [ ] Sim primer draft
  - [x] [LoL icons](https://docs.google.com/document/d/1GmLNE31gs8hQYGze3xwmN9k7B6gu7lQ7wJe2phqdH9Y/edit) for each screen created and uploaded to Drive
  - [x] LoL [metadata](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=562591429) for each screen (description, vocab words, questions for before/after sim use)
- [x] **Post-publication items** 
  - [x] Share new features, design challenges, and treats with group!
  - [x] Review legacy gold star activities, copy over if appropriate
  - [x] Deliver to [Legends of Learning](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0)
  - [x] Sim primer (create issue, publish ideally within 1 month of live sim)
  - [x] Hold postmortem if applicable N/A

## Implementation
- [x] **Repository created** (Date: 7/11/19)
  - [x] Simulation added to [responsible_dev.md](https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.md)
  - [x] Use `grunt create-sim` in perennial (see `--help` for arguments) to create the repository structure
  - [x] Collaborators added (Developer team, QA team, designers, etc)
  - [x] standard GitHub label set applied
  - [x] repository added to perennial/data/active-repos
- [x] **Development started** (Date: 10/1/2019)
- [x] **Sim is "feature complete"** (Date: 7/7/20)
- [x] **Code review completed** (Date: 9/23/20)
- [x] **Pre-publication items**
  - [x] Main screenshot (read [this](https://github.com/phetsims/QA/blob/master/doc/qa-book.md#screenshots))
  - [x] Verify credits, see #2
  - [x] Add CT tests for public query parameters
- [x] **Published** (Date: 9/1/2020) 1.1.0
  - [x] Mark the sim as published in [responsible_dev.md](https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.md)

## QA
- [x] **Legacy sim tested for bugs**; issues reported in repo (N/A since model was completely changed)
- [x] **Dev testing started** (Date: 8/27/2020) https://github.com/phetsims/QA/issues/539
- [x] **Dev testing complete** (Date: 8/28/2020) 
- [x] **First RC published** (Date: 8/28/2020) https://github.com/phetsims/QA/issues/540
  - [x] Test matrices put in [Testing Matrices Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYbW9fTGNCODdYVjQ)
- [x] **RC testing completed** (Date: 09/01/2020)

**Comment by amanda-phet** [comment]
@ariel-phet the remaining items are for you. 

I can't remember if I presented the sim at status or not :/ Thinking I didn't, so I'll add it to the agenda for this week.
