### ISSUE TITLE
verify wolves selection factor

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#172]
Like food in https://github.com/phetsims/natural-selection/issues/169, the wolves code got some cleanup.  So I think we should do another sanity check on wolves.

Things to verify:

- [ ] From #98, wolf-related query parameters values are as described in [NaturalSelectionQueryParameters.js](https://github.com/phetsims/natural-selection/blob/master/js/common/NaturalSelectionQueryParameters.js):

```
wolvesPercentToKill: [ 0.34, 0.4 ]
wolvesEnvironmentMultiplier: 2.3
```

- [ ] From #98, the percentage of bunnies to eat is randomly chosen from `wolvesPercentToKill` and used for both phenotypes.  For the phenotype whose fur does not match the environment, the percentage to eat is multiplied by `wolvesEnvironmentMultiplier`.

- [ ] From #98 and #152, bunnies whose fur matches the environment are ignored if their population is < 6, *AND* there are bunnies of the other phenotype available to eat.

- [ ] For #158, applying wolves is not skipped over in a generation clock cycle. If the "Wolves" checkboxes is checked and the bunny population is not zero, then for each generation you should see a log message that says "Applying wolves: ..."

Please verify with `?log`. Please DO NOT use `?secondsPerGeneration` and the fast-forward button together!

For any reported problems, please include:

* URL used to run the sim, with query parameters
* relevant parts of the console log
* relevant screenshots

**Comment by pixelzoom** [comment]
I went through this a couple of times, and it's ready for @amanda-phet to verify in master or [1.1.0-dev.4](https://phet-dev.colorado.edu/html/natural-selection/1.1.0-dev.4/phet/natural-selection_en_phet.html).  Feel free to assign to anyone else that you might also want to have verify.   

High priority, since this blocks the 1.0 prototype.

**Comment by pixelzoom** [comment]
>  - [ ] From #98 and #152, bunnies whose fur matches the environment are ignored if their population is < 6, AND there are bunnies of the other phenotype available to eat.

For this constraint, I realized that the recessive mutants who are waiting to meet eagerly were being excluded from "bunnies of the other phenotype".  After discussing with @amanda-phet, we decided to fix this, since it was easy and less likely to result in future confusion.  That change was made in the above commit.   

Please do any further testing with master or [1.1.0-dev.5](https://phet-dev.colorado.edu/html/natural-selection/1.1.0-dev.5/phet/natural-selection_en_phet.html).

**Comment by amanda-phet** [comment]
>- [ ] From #98 and #152, bunnies whose fur matches the environment are ignored if their population is < 6, AND there are bunnies of the other phenotype available to eat.

I am running https://phet-dev.colorado.edu/html/natural-selection/1.1.0-dev.5/phet/natural-selection_en_phet.html?log. I have a recessive brown mutation that produced the first brown bunnies in generation 3. At generation 5, There are 17 white bunnies and 2 brown bunnies. It seems like the sim calculated (from the ranges specified) that it needed to kill 16 bunnies. Why did it kill 15 white and 1 brown? The brown population is <6 and there are 16 white bunnies available. I'm not saying this is wrong, but I want to understand it, since I was expecting the brown bunnies to be ignored in this case. 

Log: 
====== Generation 5 ======
natural-selection_en_phet.html?log:81 live bunnies = 7
natural-selection_en_phet.html?log:81 dead bunnies = 68
natural-selection_en_phet.html?log:81 recessive mutants = 0
natural-selection_en_phet.html?log:81 0 bunnies died of old age
natural-selection_en_phet.html?log:81 mating 7 bunnies
natural-selection_en_phet.html?log:81 12 bunnies were born
natural-selection_en_phet.html?log:81 5 wolves were created
natural-selection_en_phet.html?log:81 Applying wolves: 17 white, 2 brown, environment=EQUATOR
natural-selection_en_phet.html?log:81 15 of 17 white bunnies were eaten by wolves
natural-selection_en_phet.html?log:81 1 of 2 brown bunnies were eaten by wolves
natural-selection_en_phet.html?log:81 5 wolves were disposed

Screenshot:
<img width="1036" alt="image" src="https://user-images.githubusercontent.com/7852916/90296957-526c5900-de4a-11ea-84dc-fc1dedf12100.png">

**Comment by amanda-phet** [comment]
>- [ ]  From #98, wolf-related query parameters values are as described in NaturalSelectionQueryParameters.js:
`wolvesPercentToKill: [ 0.34, 0.4 ]`
`wolvesEnvironmentMultiplier: 2.3`

Did you copy-paste this? The code says [0.35, 0.4], as does the sim, so I want to confirm that this is a typo, not copy-pasted from somewhere.

**Comment by pixelzoom** [comment]
Sorry, `wolvesPercentToKill: [ 0.34, 0.4 ]` is not correct, I typed it wrong when converting to `[min,max]` notation. I shouldn't just copy-pasted the code from NaturalSelectionQueryParameters.js:

```js
  wolvesPercentToKill: {
    type: 'custom',
    parse: parseRange,
    defaultValue: new Range( 0.35, 0.4 ),
    isValidValue: range => NaturalSelectionUtils.isPercentRange( range )
  },
```

**Comment by pixelzoom** [comment]
I'll investigate https://github.com/phetsims/natural-selection/issues/172#issuecomment-674295662.  In the meantime, I've added the value of `wolvesPercentToKill` that is randomly selected to the log.  You'll now see a log message like:

`randomly selected 0.3627156637753883 from wolvesPercentToKill`

**Comment by pixelzoom** [comment]
Re https://github.com/phetsims/natural-selection/issues/172#issuecomment-674295662... There were indeed 2 problems, both corrected in the above commit.

(1) The same "total bunnies" was not being used for both phenotype.  The total used for brown bunnies was the total after eating white bunnies.  I neglected to keep the total before any bunnies were eaten.

(2) If the population whose fur color matches their environment (the preferred bunnies) is too small, and there are other bunnies to eat, then we should not eat any of the preferred bunnies.  The computation for "there are other bunnies to eat" was incorrect. 

@amanda-phet please verify in master.

**Comment by pixelzoom** [comment]
@amanda-phet FYI over in #183, I changed the name of query parameter `wolvesPercentToKill` to `wolvesPercentToEatRange`.   Anything that is a range is supposed to end in a "Range" suffix, so this would have failed code review.  The value is unchanged:

```js
  // The random percentage of bunnies that will be eaten by wolves. See WolfCollection.eatBunnies.
  // Tuned in https://github.com/phetsims/natural-selection/issues/86
  wolvesPercentToEatRange: {
    type: 'custom',
    parse: parseRange,
    defaultValue: new Range( 0.35, 0.4 ),
    isValidValue: range => NaturalSelectionUtils.isPercentRange( range )
  },
```

**Comment by amanda-phet** [comment]
I think this is all looking good now. 

If we change the percentages, we will also want to update model.md. But I think the current percentages are working well.
