### ISSUE TITLE
Natural Selection 1.3 release (4/30/2021)

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#251]
From https://github.com/phetsims/natural-selection/issues/208#issuecomment-686723281, the plan for the 1.3 release is:

- [x] code review completed
- [x] Full dev test
- [x] Create 1.3 release branch
- [x] Full RC test
- [x] Publish to phet.colorado.edu and phet-io.colorado.edu
- [ ] Deliver to client

Next step is to establish dates. Assigning to @amanda-phet to lead.

**Comment by pixelzoom** [comment]
In 10/1/2020 status meeting, @kathy-phet and @ariel-phet said:

* The client doesn’t need another version in the near-term (before next summer). They will use 1.2 in their beta.  If they find any problems, a 1.2 maintenance release may be necessary. 

* When QA has an opening, move NS 1.3 through the process. Ideally sooner rather than later (early November), so it’s fresh in our minds.

* Revisit this issue near the end of October.

**Comment by pixelzoom** [comment]
Self-assigning. @ariel-phet asked me to proceed with 1.3 release, and get an RC into the QA pipeline.

**Comment by pixelzoom** [comment]
@ariel-phet You asked me to get an RC in the QA pipeline.  But I just noticed that our plan (identified in https://github.com/phetsims/natural-selection/issues/251#issue-709749752) is to do a full dev test before RC testing.  Do you want to follow that plan and start with a dev test, or modify that plan and go immediately to RC testing?

**Comment by ariel-phet** [comment]
@pixelzoom if that was the plan, lets follow it.

**Comment by pixelzoom** [comment]
I created the QA issue for dev testing 1.3.0-dev.1, see https://github.com/phetsims/QA/issues/573.  Creating of the dev version is deferred until the issue pops to the top of "Active Tests" in the QA Pipeline.

**Comment by pixelzoom** [comment]
1/14/2021 PhET-iO meeting:

The current milestone is to have 1.3 published by 3/31/2021.  I recommended getting the sim into the QA Pipeline by early February to meet this milestone.

**Comment by pixelzoom** [comment]
From the previous comment:
> I recommended getting the sim into the QA Pipeline by early February to meet that milestone. 

It's now early February.  I'm unclear about who is managing the QA queue, and I'm waiting for someone to tell me when to start the QA process.  So assigning to @arouinfar and @kathy-phet to tell me when to begin.

**Comment by pixelzoom** [comment]
2/18/21 design meeting: @amanda-phet @kathy-phet @arouinfar @pixelzoom 

We checked in on status of this release.  All sim-specific issues are addressed. We're a bit behind where we wanted to be.  But the date for this sim is flexible, and additional QA resources are coming. So @kathy-phet would like to wait before revising the milestone date.

**Comment by pixelzoom** [comment]
@zepumph in Slack for the dev test:

Michael Kauzmann:spiral_calendar_pad:  12:09 PM
When you create the NS dev test, I think it will be the first full QA test (I don't cound rc-research as "full") of master with inputEnabled changes. Could you add to that test a link to https://github.com/phetsims/scenery/issues/1116#issuecomment-802173012 which is extra testing that QA should do to test those changes.

**Comment by pixelzoom** [comment]
Milestone was changed to 4/30/21 the Project Overview, adjusting in this issue.

**Comment by pixelzoom** [comment]
On 3/19/21, @kathy-phet wrote to @amanda-phet and me on Slack:

> We just looked at the QA applications, and there are over 70! Katie will take time to work on evaluating those next week, so for the turn around you want, it might be that starting QA for NS the week of March 29 is better. I told Katie to be in touch with you Chris. Perhaps, if you take time off at the end of March, you should put it in before you leave, and hopefully it will be done by the time you get back. Steele will still be available next week.

First, I want to clarify -- it's not a matter of me wanting a specific turnaround time.  PhET process requires a relatively quick turnaround on dev tests, because there is no point in doing a dev test if it takes so long that master diverges significantly.  That said...

@KatieWoe and I checked in via Zoom today, to make sure we are all on the same page.  We are not on the same page. @KatieWoe hadn't heard about the push to week of March 29, and hadn't heard anything about Molecule Polarity https://github.com/phetsims/molecule-polarity/issues/87 (surprising because my understanding is that it's top priority).

We have a communication problem here, and I'm not in a position to resolve it.  So I am assigning this issue to @KatieWoe and @kathy-phet, to inform me when you are ready to begin dev testing.  Pick a time when the dev test can be turned around quickly. I will need 24 hours notice.

**Comment by pixelzoom** [comment]
In Slack on 3/19, @kathy-phet said:
> ... it might be that starting QA for NS the week of March 29 is better ... Perhaps, if you take time off at the end of March, you should put it in before you leave, and hopefully it will be done by the time you get back.

I had other higher-priority work this past week. And it was unclear whether any of the "blocks publication" issues (6 currently) should block NS.  So I was not able to prepare NS for QA before my vacation.  Let's adjust the date, preferrably April 5 or later.

**Comment by pixelzoom** [comment]
Dev testing started on 4/5/21 with 1.3.0-dev.3.  The QA issue is https://github.com/phetsims/QA/issues/636.

**Comment by pixelzoom** [comment]
At 4/8/21 Q2 planning meeting, dates were reviewed. We're still optimistic that we can publish by 4/30/21.

**Comment by pixelzoom** [comment]
4/13/21: 

Dev testing completed with 1.3.0-dev.1 in QA issue is phetsims/QA#636.

RC testing started with 1.3.0-rc.1. The QA issue is https://github.com/phetsims/QA/issues/641.

**Comment by pixelzoom** [comment]
1.3.0-rc.1 testing was completed on 4/23/21.

We'll need another spot-check RC.

**Comment by pixelzoom** [comment]
4/28/21: Published 1.3.0-rc.2, with QA issue https://github.com/phetsims/QA/issues/643

**Comment by zepumph** [comment]
Yes, another error about using the diff wrapper from a server, tracking in https://github.com/phetsims/phet-io-wrappers/issues/414

**Comment by zepumph** [comment]
I tried publishing an RC.3 and RC.4, but failed both times because of https://github.com/phetsims/chipper/issues/1022. I reverted back to rc.2 to keep the version numbers the same. No RC.3 yet though. I'll ask slack if someone can kick off an RC for me from a mac.

**Comment by pixelzoom** [comment]
4/28/21:

1.3.0-rc.3 testing completed.

1.3.0 production deployed:
https://phet.colorado.edu/sims/html/natural-selection/latest/natural-selection_en.html
https://phet-io.colorado.edu/sims/natural-selection/1.3/

**Comment by pixelzoom** [comment]
@kathy-phet This is ready for delivery to the client.  Please note the delivery date and assign back to me, so I can update phet-io/doc/partners.md.

**Comment by pixelzoom** [comment]
6/10/2021 phet-io meeting:

When PhET-iO publications were put on hold to address "migration issues",  @kathy-phet decided not to deliver the 1.3 version to the client.  It's noted in the PhET-iO spreadsheet, but we'll wait for the next version (1.4) to deliver to the client.

Closing.
