### ISSUE TITLE
Natural Selection 1.4 release

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#282]
6/10/2021 phet-io meeting:

gravity-and-orbits is currently in QA, to unblock PhET-iO issues. When that is completed, @kathy-phet would like to put Natural Selection into the QA pipeline for a new major release.

The plan for this release is:

- [x] dev-lite test
- [ ] full RC test
- [ ] publish
- [ ] deliver to the client

Assigning to @samreid.  When gravity-and-orbits QA is completed and there are no blocking issues, please assign this back to me and I'll proceed.

**Comment by pixelzoom** [comment]
6/17/21 phet-io meeting:

@kathy-phet would like me to publish a dev-lite test asap. I'll proceed.

**Comment by pixelzoom** [comment]
Dev-lite testing of 1.4.0-dev.1 started on 6/17/21, issue https://github.com/phetsims/QA/issues/659

**Comment by pixelzoom** [comment]
Dev-lite testing of 1.4.0-dev.1 completed on 6/21/21, see https://github.com/phetsims/QA/issues/659.  There were 0 sim-specific issues, 1 PhET-iO issue.

**Comment by pixelzoom** [comment]
@kathy-phet's instructions in Slack are to publish 1.4.0-rc.1, and put it into the QA pipeline in parallel with GAO 1.5 release, see https://github.com/phetsims/QA/issues/657.

**Comment by pixelzoom** [comment]
1.4 branch was created and 1.4.0-rc.1 was published by running `grunt rc --branch=1.4 --brands=phet,phet-io`.  The QA issue is https://github.com/phetsims/QA/issues/662.

**Comment by pixelzoom** [comment]
1.4.0-rc.1 testing was completed on 7/3/2021.

**Comment by pixelzoom** [comment]
1.4.0-rc.2 was published for RC spot-check on 7/15/21, see https://github.com/phetsims/qa/issues/672.

**Comment by pixelzoom** [comment]
1.4.0-rc.2 testing was completed on 7/19/20.  2 PhET-iO issues failed verification. 1 new PhET-iO issue was opened, see #303.

We will need another RC.

**Comment by pixelzoom** [comment]
1.4.0-rc.3 was published for RC spot-check on 7/19/21, see https://github.com/phetsims/qa/issues/674.

**Comment by pixelzoom** [comment]
1.4.0-rc.3 testing was completed on 7/23/21.  All issues passed verification, no new issues found. Ready for production deploy.

**Comment by pixelzoom** [comment]
1.4.0 was published on 7/23/21.  Spot-checked at https://phet.colorado.edu/en/simulation/natural-selection and https://phet-io.colorado.edu/sims/natural-selection/1.4.

When I published Natural Selection 1.4.0, `grunt production` had some reminders related to PhET-iO:

> Make sure that the current level of instrumentation is represented here in the Instrumentation Status Spreadsheet. On the spreadsheet, provide the version number like MAJOR.MINOR (without maintenance number) so that maintenance releases will seamlessly upgrade:
https://docs.google.com/spreadsheets/d/18_QNGuVtYtxOEKG9xRBs_PSQpyvzySF1Gk5puR-5Fv4/edit#gid=1881767354

I updated the entry for this sim to point to https://phet-io.colorado.edu/sims/natural-selection/1.4/.

> Make sure the sim is listed in perennial/data/phet-io-api-stable, if it has had a designed production release, and update the checked in API file to match the published version.

Yes, it is.

> If you are delivering this to a partner, update partners.md (phet-io/doc/partners.md) to show this delivery. Read the intro of the document to make sure that you format the entry correctly.

Natural Selection is not mentioned in partners.md.  Should it be?  Tracking in https://github.com/phetsims/phet-io/issues/1802.

**Comment by pixelzoom** [comment]
Natural Selection 1.4 release completed, closing.
